# Use a lightweight PHP image
FROM php:8.3-apache

# Install only essential PHP extensions
RUN apt-get update && \
    apt-get install -y \
    libpng-dev \
    && docker-php-ext-install gd

# Set the working directory
WORKDIR /var/www/html

# Copy composer files first for caching
COPY composer.json composer.lock ./
RUN composer install --no-dev --optimize-autoloader

# Copy the rest of the application code
COPY . .
