# Use a lightweight PHP image
FROM php:8.3-apache

# Install necessary packages, including curl for downloading Composer
RUN apt-get update && \
    apt-get install -y \
    libpng-dev \
    curl && \
    docker-php-ext-install gd

# Install Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Set the working directory
WORKDIR /var/www/html

# Copy composer files first for caching
COPY composer.json composer.lock ./
RUN composer install --no-dev --optimize-autoloader

# Copy the rest of the application code
COPY . .

# Expose the port the app runs on
EXPOSE 80
